### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by ahmedu007** [LBBO/netflix-migrate#30]
```
Logging into Netflix as something@example.com
C:\Users\ridas\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:404
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^
TypeError: Cannot read property 'data' of undefined
    at Request._callback (C:\Users\ridas\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:404:78)
    at Request.self.callback (C:\Users\ridas\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (C:\Users\ridas\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Gunzip.<anonymous> (C:\Users\ridas\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at Gunzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Its more of an issue with the `Netflix2` lib I think, I maybe wrong. But hopefully this helps

**Comment by ahmedu007** [comment]
That was my fault, sorry. I used import instead of export 😞
