### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Nullzone42** [LBBO/netflix-migrate#34]
C:\Users\BigRed-Acer\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:404
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^

TypeError: Cannot read property 'data' of undefined
    at Request._callback (C:\Users\BigRed-Acer\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:404:78)
    at Request.self.callback (C:\Users\BigRed-Acer\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Users\BigRed-Acer\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (C:\Users\BigRed-Acer\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I see the previous issue with this same context in March, but I'm definitely using the --export switch, so it's not that.

Running from Windows 10 CLI, in case it matters.

**Comment by ilTofa** [comment]
Same error on macOS 10.14.5 (18F132), npm version is '6.9.2'. I'm also using the --export switch.

**Comment by LBBO** [comment]
Sorry, but I was not able to reproduce this issue on my computer (Windows 8.1, Node v11.13.0). I will try again on another computer running Windows 10 and probably a newer Node version, but I might not get to that for a few weeks, I'm afraid. (Exams, yay!)

If you want to speed up the process, you could try debugging the code with a breakpoint at `node_modules/netflix2/lib/netflix2.js:404` and look for anything that might remotely look like an authURL inside the `self.netflixContext` object. In my case, it is still located exactly where it should be and it is a string with 42 characters that almost looks base64 encoded (except, it contains a `.`). If you are able to find the authURL, please tell me where it is located.
