### ISSUE TITLE
Cannot export profile because of Error: Invalid URI "undefined/v73fa49e3/profiles"

### ISSUE THREAD

**Issue by ely87** [LBBO/netflix-migrate#35]
Hi! I am using the following command
`netflix-migrate --email MYEMAIL@example.com --profile MYPROFILE --export netflixData.json
`

but I get the following error (nom v6.10.0 and tried on both windows, MacOS)

> Error: Invalid URI "undefined/v73fa49e3/profiles"
    at Request.init (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:273:31)
    at new Request (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:127:8)
    at request (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\index.js:53:10)
    at Netflix.__request (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\index.js:100:12)
    at Netflix.__apiRequest (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:297:8)
    at Netflix.getProfiles (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:100:8)
    at internal/util.js:286:30
    at new Promise (<anonymous>)
    at Netflix.getProfiles (internal/util.js:285:12)
    at AsyncFunction.main.getProfileGuid (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\main.js:95:28)
Error: Profile GUID could not be determined. For more information, please see previous logstatements.
    at AsyncFunction.main.getProfileGuid (C:\Users\Ely\AppData\Roaming\npm\node_modules\netflix-migrate\main.js:98:9)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

**Comment by LBBO** [comment]
Hey, #36 should fix this and has already been published. Would you mind updating your version and checking if the bug is still there?

**Comment by ely87** [comment]
I have the latest version and still get the same error :(

**Comment by LBBO** [comment]
Yes, that would be because I apparently forgot how to count correctly last evening. I fixed that mistake and it should work now with netflix-migrate v0.3.5
