### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by BoomMan8500** [LBBO/netflix-migrate#40]
I'm trying to export a Netflix profile but every time this error happens:

```
Logging into Netflix as old@example.com
C:\Users\example\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:465
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^

TypeError: Cannot read property 'data' of undefined
    at Request._callback (C:\Users\example\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:465:78)
    at Request.self.callback (C:\Users\example\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (C:\Users\example\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (C:\Users\example\AppData\Roaming\npm\node_modules\netflix-migrate\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by BoomMan8500** [comment]
My fault, I copy-pasted the password
