### ISSUE TITLE
Not working with 4K account

### ISSUE THREAD

**Issue by lpdx** [LBBO/netflix-migrate#51]
I sucessfully exported the json from my HD plan account and tested importing it to a temp profile in my account.

But when I try to import to or export from an account with 4k plan this error is returned:
```
Logging into Netflix as xxxx@xxxx
/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^

TypeError: Cannot read property 'data' of undefined
    at Request._callback (/usr/local/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465:78)
    at Request.self.callback (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/netflix-migrate/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

```

**Comment by simson** [comment]
it seems to be a duplicated of #37

**Comment by LBBO** [comment]
Yupp, @simson is exactly right.
