### ISSUE TITLE
HttpError: 403: Forbidden (Beta cookie version)

### ISSUE THREAD

**Issue by jowie** [LBBO/netflix-migrate#57]
Hi me again 🙃 thanks for all the help so far!

Looks like I've got as far as being able to login successfully with my cookie which is great, however it looks like it doesn't have permissions to update the profile data perhaps?

```
Logging into Netflix using Cookies
Login successful!
Switching to profile A
Successfully switched profile!
Reading data from netflixData.json
Found rating history and viewing history
Setting rating for Long shot: thumbs up
HttpError: 403: Forbidden
    at Netflix.__apiRequest (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix2/lib/netflix2.js:503:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Netflix.__setRating (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix2/lib/netflix2.js:355:24)
    at async Netflix.setThumbRating (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix2/lib/netflix2.js:381:5)
    at async /Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix-migrate/main.js:255:5
    at async main (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix-migrate/main.js:51:4)
Error: There was something wrong with your request. For more information, see previous log statements.
    at Netflix.__apiRequest (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix2/lib/netflix2.js:509:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Netflix.__setRating (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix2/lib/netflix2.js:355:24)
    at async Netflix.setThumbRating (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix2/lib/netflix2.js:381:5)
    at async /Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix-migrate/main.js:255:5
    at async main (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix-migrate/main.js:51:4)
Error: Couldn't set thumb rating. For more information, see previous log statements.
    at Netflix.__setRating (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix2/lib/netflix2.js:362:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Netflix.setThumbRating (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix2/lib/netflix2.js:381:5)
    at async /Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix-migrate/main.js:255:5
    at async main (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix-migrate/main.js:51:4)
Error: Could not set thumb rating for Long shot. For more information, please see previous log statements.
    at /Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix-migrate/main.js:263:10
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async main (/Users/j/.npm/_npx/f818af83f723aa7b/node_modules/netflix-migrate/main.js:51:4)

**Comment by cddigi** [comment]
I was having the exact same issue until @LBBO mentioned using both NetflixId and SecureNetflixId in https://github.com/LBBO/netflix-migrate/issues/55#issuecomment-771851497. After using this syntax, the ratings were able to be set. Viewing my ratings at https://www.netflix.com/settings/rated/ confirmed the import succeeded. 

`npx netflix-migrate --cookie "NetflixId=<value>;SecureNetflixId=<value>" --profile <name> --import netflixData.json`

**Comment by LBBO** [comment]
I'm glad you were able to find a solution to this! Just in case anyone was still facing this issue: Netflix now has [a native account transfer feature](https://help.netflix.com/en/node/124844), so I'll be archiving this project now (see #73).
