### ISSUE TITLE
Importing not working

### ISSUE THREAD

**Issue by LaMpiR** [LBBO/netflix-migrate#64]
Hi.

So, installed nodejs and npm on ubuntu server and exported everything without errors.
Importing resulted in an error:

```
user@ubuntulamp:~/netflix/netflix-migrate-master$ npx netflix-migrate --email email@email.email --profile Sofi --import netflixData.json
npx: installed 140 in 11.285s
Password:
Logging into Netflix as email@email.email
/home/user/.npm/_npx/13694/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^

TypeError: Cannot read property 'data' of undefined
    at Request._callback (/home/user/.npm/_npx/13694/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465:78)
    at Request.self.callback (/home/user/.npm/_npx/13694/lib/node_modules/netflix-migrate/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/user/.npm/_npx/13694/lib/node_modules/netflix-migrate/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at Gunzip.<anonymous> (/home/user/.npm/_npx/13694/lib/node_modules/netflix-migrate/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at Gunzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
user@ubuntulamp:~/netflix/netflix-migrate-master$
```

**Comment by card13** [comment]
Same error on Ubuntu 21.04.

**Comment by LBBO** [comment]
Closing this as a duplicate and since I'm archiving the project due to [Netflix adding native support for account migration](https://help.netflix.com/en/node/124844).
