### ISSUE TITLE
Beta cookie can't login

### ISSUE THREAD

**Issue by Typhon0** [LBBO/netflix-migrate#66]
Hello I try to login with the cookie option and I got this error : 

```
Using new Netflix2 class!
Logging into Netflix using Cookies
(node:28148) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Error: We are having technical difficulties and are actively working on a fix. Please try again in a few minutes.
    at Netflix.__postLoginForm (S:\Git_repos\netflix-migrate\node_modules\netflix2\lib\netflix2.js:478:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Netflix.login (S:\Git_repos\netflix-migrate\node_modules\netflix2\lib\netflix2.js:70:9)
    at async main (S:\Git_repos\netflix-migrate\main.js:24:3)
Error: Check your credentials. For more information, see previous log statements.
    at Netflix.__postLoginForm (S:\Git_repos\netflix-migrate\node_modules\netflix2\lib\netflix2.js:482:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Netflix.login (S:\Git_repos\netflix-migrate\node_modules\netflix2\lib\netflix2.js:70:9)
    at async main (S:\Git_repos\netflix-migrate\main.js:24:3)
Error: Something went wrong. For more information, see previous log statements.
    at Netflix.login (S:\Git_repos\netflix-migrate\node_modules\netflix2\lib\netflix2.js:83:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (S:\Git_repos\netflix-migrate\main.js:24:3)
```

Thanks

**Comment by snwagbata** [comment]
Log out of netflix. Clear cookies and try again

**Comment by Typhon0** [comment]
I tried this today and same error again

**Comment by origamiofficial** [comment]
Use this docker container, which requires only two Netflix cookie & it's based on this code.
https://github.com/origamiofficial/docker-netflix-migrate/tree/main/Beta

**Comment by LBBO** [comment]
Hey everyone! Sorry for not helping out with this issue for so long, I was just really busy and, quite frankly, fed up with playing catchup with changes to Netflix's API or DOM structure or whatever every couple of months.

However, there's some good news! In case anyone hasn't heard, Netflix now officially supports account migration, including viewing history! For more details, see their [official documentation](https://help.netflix.com/en/node/124844). Since that feature implements exactly what this project was aiming to do, I will officially archive this repository now (see #73). Feel free to reach out if you have any further questions!
