### ISSUE TITLE
Cant import data to new netflix account

### ISSUE THREAD

**Issue by ChunkyCookie88** [LBBO/netflix-migrate#70]
C:\Users\perchr>
C:\Users\perchr>netflix-migrate --email example@email.com --profile Christoble --import downloads\netflixdata.json  (_this is the location I exported the data to before anyone says anything about it_)
Password:
Logging into Netflix as example@email.com
C:\Users\perchr\bin\nodejs\node-v16.15.1-win-x64\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:465
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^

TypeError: Cannot read properties of undefined (reading 'data')
    at Request._callback (C:\Users\perchr\bin\nodejs\node-v16.15.1-win-x64\node_modules\netflix-migrate\node_modules\netflix2\lib\netflix2.js:465:78)
    at Request.self.callback (C:\Users\perchr\bin\nodejs\node-v16.15.1-win-x64\node_modules\netflix-migrate\node_modules\request\request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (C:\Users\perchr\bin\nodejs\node-v16.15.1-win-x64\node_modules\netflix-migrate\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:527:28)
    at Gunzip.<anonymous> (C:\Users\perchr\bin\nodejs\node-v16.15.1-win-x64\node_modules\netflix-migrate\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at Gunzip.emit (node:events:527:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

C:\Users\perchr>

**Comment by webknjaz** [comment]
I've re-run the export command just now, and it didn't crash with this traceback, but succeeded. I suppose it may've been a temporary issue or a corner case happening in rare circumstances.

**Comment by ChrisChiera** [comment]
This is happening for me as well. Exported the data back in April. Attempting to import now from a Mac using latest Ventura beta.

`Logging into Netflix as [myemail]
/opt/homebrew/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465
      self.authUrls[url] = context.netflix.reactContext.models.memberContext.data.userInfo.authURL
                                                                             ^

TypeError: Cannot read properties of undefined (reading 'data')
    at Request._callback (/opt/homebrew/lib/node_modules/netflix-migrate/node_modules/netflix2/lib/netflix2.js:465:78)
    at Request.self.callback (/opt/homebrew/lib/node_modules/netflix-migrate/node_modules/request/request.js:185:22)
    at Request.emit (node:events:527:28)
    at Request.<anonymous> (/opt/homebrew/lib/node_modules/netflix-migrate/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:527:28)
    at Gunzip.<anonymous> (/opt/homebrew/lib/node_modules/netflix-migrate/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:641:28)
    at Gunzip.emit (node:events:527:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Node.js v17.8.0
`

**Comment by ChrisChiera** [comment]
Figured it out based on a similar issue on here. The issue is that when it asks for Password, I assume it was asking for my computer password but it meant "Netflix" password. Entering that worked!

**Comment by LBBO** [comment]
Hey everyone! Sorry for not helping out with this issue for so long, I was just really busy and, quite frankly, fed up with playing catchup with changes to Netflix's API or DOM structure or whatever every couple of months.

However, there's some good news! In case anyone hasn't heard, Netflix now officially supports account migration, including viewing history! For more details, see their [official documentation](https://help.netflix.com/en/node/124844). Since that feature implements exactly what this project was aiming to do, I will officially archive this repository now (see #73). Feel free to reach out if you have any further questions!
